/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8mb4 */;
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS;
SET @@SESSION.SQL_MODE='';

LOCK TABLES `users` WRITE;
INSERT INTO `users` VALUES (1,'alice');
INSERT INTO `users` VALUES (2,'ENGINE=InnoDB is inside data, must NOT be stripped');
UNLOCK TABLES;

CREATE TABLE `users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=100 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC;

DELIMITER $$
CREATE PROCEDURE hello()
BEGIN
  SELECT 1;
END$$
DELIMITER ;
