"""阶段4: 修饰符清理 — 删除/替换源方言特有的修饰符和子句。"""
import re
from converter.pipeline import Rule
from converter.capabilities import (
    CAP_UNSIGNED, CAP_ZEROFILL, CAP_ENGINE, CAP_CHARSET, CAP_COLLATE,
    CAP_CASCADE, CAP_ON_UPDATE_TIMESTAMP, CAP_ROW_FORMAT,
    CAP_AUTO_INCREMENT, CAP_TYPE_PG_TYPE_CAST, CAP_TYPE_EXTENSION,
)

MODIFIER_RULES: list[Rule] = [
    Rule("strip_unsigned", CAP_UNSIGNED,
         re.compile(r"\s+unsigned\b", re.IGNORECASE),
         replacement="", scope="line", skip_insert=True,
         desc="删除 UNSIGNED"),
    Rule("strip_zerofill", CAP_ZEROFILL,
         re.compile(r"\s+zerofill\b", re.IGNORECASE),
         replacement="", scope="line", skip_insert=True,
         desc="删除 ZEROFILL"),
    Rule("strip_engine_clause", CAP_ENGINE,
         re.compile(r"\s*ENGINE\s*=\s*\w+", re.IGNORECASE),
         replacement="", scope="line", skip_insert=True,
         desc="删除 ENGINE=xxx"),
    Rule("strip_default_charset", CAP_CHARSET,
         re.compile(r"\s*(DEFAULT\s+)?(CHARACTER\s+SET|CHARSET)\s*=?\s*\w+(\s+COLLATE\s*=?\s*\w+)?", re.IGNORECASE),
         replacement="", scope="line", skip_insert=True,
         desc="删除 DEFAULT CHARSET / COLLATE"),
    Rule("strip_collate_standalone", CAP_COLLATE,
         re.compile(r"\s+COLLATE\s+\w+", re.IGNORECASE),
         replacement="", scope="line", skip_insert=True,
         desc="删除独立 COLLATE"),
    Rule("strip_column_charset", CAP_CHARSET,
         re.compile(r"\s+(CHARACTER\s+SET|CHARSET)\s+\w+(\s+COLLATE\s+\w+)?", re.IGNORECASE),
         replacement="", scope="line", skip_insert=True,
         desc="删除列级 CHARACTER SET / COLLATE"),
    Rule("strip_cascade", CAP_CASCADE,
         re.compile(r"\s+CASCADE\b", re.IGNORECASE),
         replacement="", scope="line", skip_insert=True,
         desc="删除 CASCADE"),
    Rule("strip_on_update_timestamp", CAP_ON_UPDATE_TIMESTAMP,
         re.compile(r"\s+ON\s+UPDATE\s+CURRENT_TIMESTAMP(\s*\(\d+\))?", re.IGNORECASE),
         replacement="", scope="line", skip_insert=True,
         desc="删除 ON UPDATE CURRENT_TIMESTAMP"),
    Rule("strip_table_auto_increment", CAP_AUTO_INCREMENT,
         re.compile(r"\s*AUTO_INCREMENT\s*=\s*\d+", re.IGNORECASE),
         replacement="", scope="line", skip_insert=True,
         desc="删除表级 AUTO_INCREMENT=N"),
    Rule("strip_row_format", CAP_ROW_FORMAT,
         re.compile(r"\s*(ROW_FORMAT|KEY_BLOCK_SIZE|PACK_KEYS|STATS_PERSISTENT|STATS_AUTO_RECALC|DELAY_KEY_WRITE)\s*=\s*\w+", re.IGNORECASE),
         replacement="", scope="line", skip_insert=True,
         desc="删除 ROW_FORMAT 等表选项"),
    Rule("strip_pg_type_cast", CAP_TYPE_PG_TYPE_CAST,
         re.compile(r"::\w+"),
         replacement="", scope="line", skip_insert=False,
         desc="删除 PG ::type 类型转换"),
    Rule("strip_pg_extension", CAP_TYPE_EXTENSION,
         re.compile(r"^\s*CREATE\s+EXTENSION\s+.*?;\s*$", re.IGNORECASE | re.MULTILINE),
         replacement="", scope="global", skip_insert=True,
         desc="删除 CREATE EXTENSION"),
]
