"""阶段3: 类型映射 — 源方言特有类型 → 目标方言兼容类型。"""
import re
from converter.pipeline import Rule
from converter.capabilities import (
    CAP_TYPE_TINYINT, CAP_TYPE_MEDIUMINT, CAP_TYPE_INT_DISPLAY_WIDTH,
    CAP_TYPE_BIGINT_DISPLAY_WIDTH, CAP_TYPE_SMALLINT_DISPLAY_WIDTH,
    CAP_TYPE_INTEGER_DISPLAY_WIDTH, CAP_TYPE_TINYTEXT,
    CAP_TYPE_BLOB, CAP_TYPE_DATETIME, CAP_TYPE_TIMESTAMP,
    CAP_TYPE_YEAR, CAP_TYPE_DOUBLE, CAP_TYPE_FLOAT, CAP_TYPE_ENUM,
    CAP_TYPE_SET, CAP_TYPE_BIT, CAP_TYPE_BIT_LITERAL,
    CAP_TYPE_VARCHAR2, CAP_TYPE_NUMBER, CAP_TYPE_ORACLE_DATE,
    CAP_TYPE_LONG_RAW, CAP_TYPE_RAW,
    CAP_TYPE_SERIAL, CAP_TYPE_BOOLEAN, CAP_TYPE_BYTEA,
    CAP_TYPE_DOUBLE_PRECISION, CAP_TYPE_TEXT,
    CAP_AUTO_INCREMENT, CAP_TYPE_AUTOINCREMENT,
)

TYPE_MAPPING_RULES: list[Rule] = [
    # ── MySQL 整数类型 ──
    Rule("convert_tinyint_type", CAP_TYPE_TINYINT,
         re.compile(r"\btinyint\b(\s*\(\d+\))?", re.IGNORECASE),
         replacement="SMALLINT", scope="line", skip_insert=True,
         desc="TINYINT → SMALLINT"),
    Rule("convert_mediumint_type", CAP_TYPE_MEDIUMINT,
         re.compile(r"\bmediumint\b(\s*\(\d+\))?", re.IGNORECASE),
         replacement="INTEGER", scope="line", skip_insert=True,
         desc="MEDIUMINT → INTEGER"),
    Rule("convert_int_display_width", CAP_TYPE_INT_DISPLAY_WIDTH,
         re.compile(r"\bint\b(\s*\(\d+\))?", re.IGNORECASE),
         replacement="INTEGER", scope="line", skip_insert=True,
         desc="INT(N) → INTEGER"),
    Rule("convert_integer_display_width", CAP_TYPE_INTEGER_DISPLAY_WIDTH,
         re.compile(r"\binteger\b(\s*\(\d+\))?", re.IGNORECASE),
         replacement="INTEGER", scope="line", skip_insert=True,
         desc="INTEGER(N) → INTEGER"),
    Rule("convert_bigint_display_width", CAP_TYPE_BIGINT_DISPLAY_WIDTH,
         re.compile(r"\bbigint\b(\s*\(\d+\))?", re.IGNORECASE),
         replacement="BIGINT", scope="line", skip_insert=True,
         desc="BIGINT(N) → BIGINT"),
    Rule("convert_smallint_display_width", CAP_TYPE_SMALLINT_DISPLAY_WIDTH,
         re.compile(r"\bsmallint\b(\s*\(\d+\))?", re.IGNORECASE),
         replacement="SMALLINT", scope="line", skip_insert=True,
         desc="SMALLINT(N) → SMALLINT"),

    # ── MySQL 日期时间 ──
    Rule("convert_datetime_type", CAP_TYPE_DATETIME,
         re.compile(r"\bdatetime\b", re.IGNORECASE),
         replacement="TIMESTAMP", scope="line", skip_insert=True,
         desc="datetime → TIMESTAMP"),
    Rule("convert_year_type", CAP_TYPE_YEAR,
         re.compile(r"\byear\b(\s*\(\s*4\s*\))?", re.IGNORECASE),
         replacement="SMALLINT", scope="line", skip_insert=True,
         desc="YEAR → SMALLINT"),

    # ── MySQL 文本/二进制 ──
    Rule("convert_text_types", CAP_TYPE_TINYTEXT,
         re.compile(r"\b(tinytext|mediumtext|longtext)\b", re.IGNORECASE),
         replacement="TEXT", scope="line", skip_insert=True,
         desc="TINYTEXT/MEDIUMTEXT/LONGTEXT → TEXT"),
    Rule("convert_blob_types", CAP_TYPE_BLOB,
         re.compile(r"\b(tinyblob|mediumblob|longblob|blob)\b", re.IGNORECASE),
         replacement="BYTEA", scope="line", skip_insert=True,
         desc="BLOB 系列 → BYTEA"),

    # ── MySQL ENUM/SET ──
    Rule("convert_enum_type", CAP_TYPE_ENUM,
         re.compile(r"\benum\s*\([^)]*\)", re.IGNORECASE),
         replacement="VARCHAR(255)", scope="line", skip_insert=True,
         desc="ENUM → VARCHAR(255)"),
    Rule("convert_set_type", CAP_TYPE_SET,
         re.compile(r"\bset\s*\([^)]*\)", re.IGNORECASE),
         replacement="VARCHAR(255)", scope="line", skip_insert=True,
         desc="SET → VARCHAR(255)"),

    # ── MySQL 浮点 ──
    Rule("convert_double_type", CAP_TYPE_DOUBLE,
         re.compile(r"\bdouble\b(?!\s+precision)", re.IGNORECASE),
         replacement="DOUBLE PRECISION", scope="line", skip_insert=True,
         desc="DOUBLE → DOUBLE PRECISION"),
    Rule("convert_float_type", CAP_TYPE_FLOAT,
         re.compile(r"\bfloat\b(\s*\(\d+,\d+\))?", re.IGNORECASE),
         replacement="REAL", scope="line", skip_insert=True,
         desc="FLOAT → REAL"),

    # ── MySQL BIT ──
    Rule("convert_bit_type", CAP_TYPE_BIT,
         re.compile(r"\bbit\s*\(\s*1\s*\)", re.IGNORECASE),
         replacement="SMALLINT", scope="line", skip_insert=False,
         desc="bit(1) → SMALLINT"),
    Rule("convert_bit_literal", CAP_TYPE_BIT_LITERAL,
         re.compile(r"\bb'(0|1)'", re.IGNORECASE),
         replacement=r"'\1'", scope="line", skip_insert=False,
         desc="b'0'/b'1' → 普通整数"),

    # ── MySQL AUTO_INCREMENT → SQLite AUTOINCREMENT ──
    Rule("convert_auto_increment", CAP_AUTO_INCREMENT,
         target_capability=CAP_TYPE_AUTOINCREMENT,
         pattern=re.compile(r"\bAUTO_INCREMENT\b", re.IGNORECASE),
         replacement="AUTOINCREMENT", scope="line", skip_insert=True,
         desc="AUTO_INCREMENT → AUTOINCREMENT"),

    # ── Oracle 类型 ──
    Rule("convert_long_raw_type", CAP_TYPE_LONG_RAW,
         re.compile(r"\blong\s+raw\b", re.IGNORECASE),
         replacement="BYTEA", scope="line", skip_insert=True,
         desc="LONG RAW → BYTEA"),
    Rule("convert_varchar2_type", CAP_TYPE_VARCHAR2,
         re.compile(r"\b(varchar2|nvarchar2|varchar|nvarchar|char|nchar|clob|nclob|long)\b(\s*\(\d+\))?", re.IGNORECASE),
         replacement="TEXT", scope="line", skip_insert=True,
         desc="Oracle 字符串 → TEXT"),
    Rule("convert_oracle_number_precision", CAP_TYPE_NUMBER,
         re.compile(r"\bnumber\b(\s*\(\d+,\d+\))", re.IGNORECASE),
         replacement=r"REAL", scope="line", skip_insert=True,
         desc="NUMBER(N,M) → REAL"),
    Rule("convert_oracle_number", CAP_TYPE_NUMBER,
         re.compile(r"\bnumber\b(\s*\(\d+\))?", re.IGNORECASE),
         replacement="INTEGER", scope="line", skip_insert=True,
         desc="NUMBER(N) → INTEGER"),
    Rule("convert_oracle_date_type", CAP_TYPE_ORACLE_DATE,
         re.compile(r"\bdate\b", re.IGNORECASE),
         replacement="TIMESTAMP", scope="line", skip_insert=True,
         desc="Oracle DATE → TIMESTAMP"),
    Rule("convert_raw_type", CAP_TYPE_RAW,
         re.compile(r"\b(raw|blob)\b(\s*\(\d+\))?", re.IGNORECASE),
         replacement="BLOB", scope="line", skip_insert=True,
         desc="RAW/BLOB → BLOB"),

    # ── PG 类型 → 其他 ──
    Rule("convert_serial_type", CAP_TYPE_SERIAL,
         re.compile(r"\b(serial|bigserial|smallserial)\b", re.IGNORECASE),
         replacement="INTEGER", scope="line", skip_insert=True,
         desc="SERIAL → INTEGER"),
    Rule("convert_boolean_type", CAP_TYPE_BOOLEAN,
         re.compile(r"\bboolean\b", re.IGNORECASE),
         replacement="INTEGER", scope="line", skip_insert=True,
         desc="BOOLEAN → INTEGER"),
    Rule("convert_bytea_type", CAP_TYPE_BYTEA,
         re.compile(r"\bbytea\b", re.IGNORECASE),
         replacement="BLOB", scope="line", skip_insert=True,
         desc="BYTEA → BLOB"),
    Rule("convert_timestamp_type", CAP_TYPE_TIMESTAMP,
         re.compile(r"\btimestamp\b(\s*\(\d+\))?", re.IGNORECASE),
         replacement="TEXT", scope="line", skip_insert=True,
         desc="TIMESTAMP → TEXT"),
    Rule("convert_double_precision", CAP_TYPE_DOUBLE_PRECISION,
         re.compile(r"\bdouble\s+precision\b", re.IGNORECASE),
         replacement="REAL", scope="line", skip_insert=True,
         desc="DOUBLE PRECISION → REAL"),
    Rule("convert_pg_text_types", CAP_TYPE_TEXT,
         re.compile(r"\b(varchar|char|text)\b(\s*\(\d+\))?", re.IGNORECASE),
         replacement="TEXT", scope="line", skip_insert=True,
         desc="PG 字符串 → TEXT"),
    Rule("convert_pg_integer_types", CAP_TYPE_SERIAL,
         re.compile(r"\b(smallint|integer|int|bigint|int2|int4|int8)\b", re.IGNORECASE),
         replacement="INTEGER", scope="line", skip_insert=True,
         desc="PG 整数 → INTEGER"),
]
