"""数据库能力标签常量。

每个能力代表一个数据库特性。Dialect 声明自己支持哪些能力，
Rule 通过能力匹配决定是否执行（源有、目标无 → 执行）。
"""

# ── 语法 / 语句能力 ──
CAP_ENGINE = "engine"
CAP_CHARSET = "charset"
CAP_COLLATE = "collate"
CAP_UNSIGNED = "unsigned"
CAP_ZEROFILL = "zerofill"
CAP_AUTO_INCREMENT = "auto_increment"
CAP_ENUM = "enum"
CAP_SET = "set"
CAP_CASCADE = "cascade"
CAP_DELIMITER = "delimiter"
CAP_LOCK_TABLES = "lock_tables"
CAP_SESSION_VARS = "session_vars"
CAP_FOREIGN_KEY_CHECKS = "foreign_key_checks"
CAP_USING_BTREE = "using_btree"
CAP_ROW_FORMAT = "row_format"
CAP_ON_UPDATE_TIMESTAMP = "on_update_current_timestamp"
CAP_VERSION_COMMENT = "version_comment"
CAP_ORACLE_HINTS = "oracle_hints"

# ── 标识符能力 ──
CAP_BACKTICK_QUOTE = "backtick_quote"
CAP_DOUBLE_QUOTE = "double_quote"

# ── 类型能力 ──
CAP_TYPE_TINYINT = "type_tinyint"
CAP_TYPE_MEDIUMINT = "type_mediumint"
CAP_TYPE_INT_DISPLAY_WIDTH = "type_int_display_width"
CAP_TYPE_BIGINT_DISPLAY_WIDTH = "type_bigint_display_width"
CAP_TYPE_SMALLINT_DISPLAY_WIDTH = "type_smallint_display_width"
CAP_TYPE_INTEGER_DISPLAY_WIDTH = "type_integer_display_width"
CAP_TYPE_TINYTEXT = "type_tinytext"
CAP_TYPE_MEDIUMTEXT = "type_mediumtext"
CAP_TYPE_LONGTEXT = "type_longtext"
CAP_TYPE_TEXT = "type_text"
CAP_TYPE_BLOB = "type_blob"
CAP_TYPE_DATETIME = "type_datetime"
CAP_TYPE_TIMESTAMP = "type_timestamp"
CAP_TYPE_YEAR = "type_year"
CAP_TYPE_DOUBLE = "type_double"
CAP_TYPE_FLOAT = "type_float"
CAP_TYPE_ENUM = "type_enum"
CAP_TYPE_SET = "type_set"
CAP_TYPE_BIT = "type_bit"
CAP_TYPE_BIT_LITERAL = "type_bit_literal"
CAP_TYPE_VARCHAR2 = "type_varchar2"
CAP_TYPE_NVARCHAR2 = "type_nvarchar2"
CAP_TYPE_NUMBER = "type_number"
CAP_TYPE_CLOB = "type_clob"
CAP_TYPE_NCLOB = "type_nclob"
CAP_TYPE_BLOB_ORACLE = "type_blob_oracle"
CAP_TYPE_LONG = "type_long"
CAP_TYPE_LONG_RAW = "type_long_raw"
CAP_TYPE_RAW = "type_raw"
CAP_TYPE_NCHAR = "type_nchar"
CAP_TYPE_ORACLE_DATE = "type_oracle_date"
CAP_TYPE_SERIAL = "type_serial"
CAP_TYPE_BIGSERIAL = "type_bigserial"
CAP_TYPE_BOOLEAN = "type_boolean"
CAP_TYPE_BYTEA = "type_bytea"
CAP_TYPE_DOUBLE_PRECISION = "type_double_precision"
CAP_TYPE_PG_TYPE_CAST = "type_pg_type_cast"
CAP_TYPE_EXTENSION = "type_extension"
CAP_TYPE_AUTOINCREMENT = "type_autoincrement"
